FROM golang:1.24.3-alpine

RUN apk add --no-cache git ca-certificates tzdata curl unzip && \
    curl -L https://github.com/cosmtrek/air/releases/download/v1.49.0/air_1.49.0_linux_amd64.tar.gz | tar -xz && \
    mv air /usr/local/bin/air

WORKDIR /app
COPY . .

EXPOSE 8080

CMD ["air"]