FROM public.ecr.aws/docker/library/golang:1.26.1-alpine

ENV GIN_MODE=debug

RUN apk add --no-cache git ca-certificates tzdata && \
    go install github.com/air-verse/air@v1.65.1

WORKDIR /app
COPY . .

EXPOSE 8080

CMD ["air"]